services:
  leila-admin:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: leila-admin:latest
    container_name: leila-admin-container
    ports:
      - 3000:3000
    extra_hosts:
      - "localhost:192.168.1.13"  
    volumes:
      - D:\EIU\Web-Examples\leila\leila-admin:/home/node
    command: "npm run dev"    
  leila-store:
    build: 
      context: ../leila-store
      dockerfile: ../leila-store/Dockerfile
    image: leila-store:latest
    container_name: leila-store-container
    ports:
      - 3001:3001
    extra_hosts:
      - "localhost:192.168.1.13"  
    volumes:
      - D:\EIU\Web-Examples\leila\leila-store:/home/node
    command: "npm run dev"



